/* data load */
INSERT INTO ROOM (ROOM_CD, FLOOR_NBR, ROOM_NM, ROOM_DESC, ROOM_SEATS_NBR) VALUES ( 'RAMS-4', 4, 'Rams', 'Rams room', 20 );
INSERT INTO ROOM (ROOM_CD, FLOOR_NBR, ROOM_NM, ROOM_DESC, ROOM_SEATS_NBR) VALUES ( 'CARDINALS-4', 4, 'Cardinals-4', 'Cardinals room', 30 );
